export const SHOP_REGISTER = 'SHOP_REGISTER'
export const SHOP_REGISTER_SUCCESS = 'SHOP_REGISTER_SUCCESS'
export const SHOP_REGISTER_FAILED = 'SHOP_REGISTER_FAILED'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const CHECK_LOGIN = 'CHECK_LOGIN'
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS'
export const CHECK_LOGIN_FAIL = 'CHECK_LOGIN_FAIL'

export const VERSION_UPDATE = 'VERSION_UPDATE'
export const VERSION_UPDATE_SUCCESS = 'VERSION_UPDATE_SUCCESS'
export const VERSION_UPDATE_FAILED = 'VERSION_UPDATE_FAILED'

export const REQUEST_TRANSACTION = 'REQUEST_TRANSACTION'
export const REQUEST_TRANSACTION_SUCCESS = 'REQUEST_TRANSACTION_SUCCESS'
export const REQUEST_TRANSACTION_FAILED = 'REQUEST_TRANSACTION_FAILED'

export const REQUEST_REVERT = 'REQUEST_REVERT'
export const REQUEST_REVERT_SUCCESS = 'REQUEST_REVERT_SUCCESS'
export const REQUEST_REVERT_FAILED = 'REQUEST_REVERT_FAILED'

export const CHECK_SHOP_INFO = 'CHECK_SHOP_INFO'
export const CHECK_SHOP_INFO_SUCCESS = 'CHECK_SHOP_INFO_SUCCESS'
export const CHECK_SHOP_INFO_FAILED = 'CHECK_SHOP_INFO_FAILED'

export const SETUP_API = "SETUP_API"
export const CLEAR_API = "CLEAR_API"

export const SETUP_API_SUCCESS = "SETUP_API_SUCCESS"
export const SETUP_API_FAIL = "SETUP_API_FAIL"

export const CLEAR_REGISTER = 'CLEAR_REGISTER'

export const CHANGE_LOCAL_LANGUAGE = "CHANGE_LOCAL_LANGUAGE"

export const SAVE_PROFILE = "SAVE_PROFILE"

export const UPDATE_SHOP_INFO = 'UPDATE_SHOP_INFO'

export const SETUP_PRINTER = 'SETUP_PRINTER'

export const SERVER_PATH = 'SERVER_PATH'
export const NAV_INDEX ={
    STAFF:1,
    TEACHER:2,
    STUDENT:3,
}