const image = {
    icon_email: require('../images/email.png'),
    icon_password: require('../images/password.png'),
    iconShop: require('../images/new_logo.png'),
    iconFinger: require('../images/fingerprint.png'),
    iconBio: require('../images/biometric.png'),
    iconExit: require('../images/exit.png'),
    iconHelp: require('../images/help.png'),
    iconId: require('../images/id.png'),
    iconLocation: require('../images/location.png'),
    iconPayment: require('../images/payment.png'),
    iconProfile: require('../images/profile.png'),
    iconReport: require('../images/report.png'),
    iconServer: require('../images/server.png'),
    iconRevertMoney: require('../images/revert_money.png'),
    iconSetting: require('../images/setting.png'),
    iconShare: require('../images/share.png'),
    iconShopInfo: require('../images/shopInfo.png'),
    iconTelephone: require('../images/telephone.png'),
    iconClose: require('../images/close.png'),
    iconHome: require('../images/home.png'),
    iconSelectImage: require('../images/select_image.png'),
    iconPrinter: require('../images/printer.png'),
    icLaos:require('../images/flag_laos.png'),
    icEnglish: require('../images/flag_england.png'),
    icScanner: require('../images/QRCode.png'),
    icCamera: require('../images/camera.png'),
    iconChart: require('../images/chart.png'),
    iconShareIcon: require('../images/1635.jpg'),

    icSlideFirst: require('../images/slide_show/bann_parking.jpg'),
    icSlideSecond: require('../images/slide_show/parking_composition_vector.jpg'),
    icSlideTird: require('../images/slide_show/reverse_parking_preview.jpg')
}

export default image